### ISSUE TITLE
B9PartSwitch Warning on part B10.IDA.

### ISSUE THREAD

**Issue by kailGH** [benjee10/Benjee10_sharedAssets#4]
v0.2.2
KSP Log.. 
[WRN 07:00:04.886] Warning on PartSubtype Blue on module ModuleB9PartSwitch (moduleID='handrails') on part unknownPart: Texture 'Benjee10_sharedAssets/Parts/APAS/ht2_details_shared_B' not found!
[LOG 07:00:04.890] PartLoader: Part 'Benjee10_sharedAssets/Parts/APAS/B10_IDA/B10_IDA' has no database record. Creating.
[LOG 07:00:04.890] [DragCubeSystem]: Drag cubes not found or cannot be read for part Part. Generating New drag cubes.
[LOG 07:00:04.894] DragCubeSystem: Creating drag cubes for part 'B10.IDA'
[WRN 07:00:04.918] Warning on PartSubtype Blue on module ModuleB9PartSwitch (moduleID='handrails') on part B10.IDA: Texture 'Benjee10_sharedAssets/Parts/APAS/ht2_details_shared_B' not found! ..

B9 Warning Image: https://imgur.com/a/Z9W9KPF

And on typing this, is this a B10_IDA vs B10.IDA typo?

**Comment by benjee10** [comment]
I'm unable to replicate this - please ensure you're using the latest version of Benjee10_sharedAssets and have done a clean install. If the issue persists, please could you check that the ht2_details_shared_B.DDS file is present in your GameData/Benjee10_sharedAssets/Parts/APAS/ folder.

**Comment by kailGH** [comment]
OK, thanks. It must be a problem at my end. I found that file in GameData/Benjee10_Orion/Orion/Parts (Artemis Construction Kit) rather than Shared Assets. CKAN had updated Artemis to 1.4.0 several hours before Shared Assets was updated v0.2.2, Something must have broke in CKAN, I'll re-install both. Thanks again.
